# Generated by Django 6.1 on 2026-08-20 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_mailbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_archived',
            new_name='archived_by',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='team_mailbox.message'),
        ),
    ]
