# Generated by Django 6.1 on 2026-08-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_mailbox', '0002_rename_is_archived_message_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
