# Generated by Django 6.1 on 2026-08-20 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmployeeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'profile__role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_contacts', to=settings.AUTH_USER_MODEL)),
                ('external_user', models.ForeignKey(limit_choices_to={'profile__role__in': ['CLIENT', 'CUSTOMER']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client/Customer Access Permission',
                'verbose_name_plural': 'Client/Customer Access Permissions',
                'unique_together': {('employee', 'external_user')},
            },
        ),
    ]
